### ISSUE TITLE
Identity Name is null

### ISSUE THREAD

**Issue by alkampfergit** [flakey-bit/DotNetDigestAuth#24]
I've implemented DIGEST auth with your library (kudo it seems to work fine). I have only a small question, the User object that get injected into the ASP.NET core controller has a username null and a claim DIGEST_AUTHENTICATION_NAME that contains the username used to authenticate.

My question is: is there an option to let the username to be also the Name of generated user?

![image](https://github.com/flakey-bit/DotNetDigestAuth/assets/358545/8cebf66a-9f64-4fea-b285-c1b04ffb0df3)

**Comment by flakey-bit** [comment]
Hey @alkampfergit!

Thanks for the issue. I believe the `Name` property on the identity is based on the presence of a `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` claim ([see this answer](https://stackoverflow.com/a/53906240)).

I think we can use the constant `ClaimsIdentity::DefaultNameClaimType` (`System.Security.Claims`).

I don't think we need to make this opt-in; **I think we should set this claim by default**. 

I think it should be as simple as updating the authentication handlers:
* [ASP.NET classic](https://github.com/flakey-bit/DotNetDigestAuth/blob/78682fb0b8867f7185c8e76b3b5097768cdf095e/DigestAuthentication.AspNetClassic/DigestAuthenticationHandler.cs#L37)
* [ASP.NET core](https://github.com/flakey-bit/DotNetDigestAuth/blob/78682fb0b8867f7185c8e76b3b5097768cdf095e/DigestAuthentication.AspNetCore/DigestAuthenticationHandler.cs#L59)

to add an additional claim (we'll want to retain the custom `DigestAuthImplementation.DigestAuthenticationClaimName` claim).

Would you like to have a go at a PR?

Also: Interested to hear about your use-case for Digest authentication.

**Comment by alkampfergit** [comment]
Pull request was done.

My use case is: we have a software that implements WebDAV protocol to allow office suite to directly open files from our software. If we Do not have Active directory we cannot rely on NTLM/Kerberos, and using DIGEST is the way to go with a simple solution now that BASIC auth was disabled in microsoft Word and in the whole office routine.

**Comment by flakey-bit** [comment]
This should be fixed now.
